import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Route, Routes } from 'react-router-dom';
import { Header } from './components/Header';
import { HomePage } from './pages/HomePage';
import { LoginPage } from './pages/LoginPage';
import { RegisterPage } from './pages/RegisterPage';
import { CasesPage } from './pages/CasesPage';
import { CaseDetailsPage } from './pages/CaseDetailsPage';
import { AnalyticsPage } from './pages/AnalyticsPage';
import { VolunteerPage } from './pages/VolunteerPage';
import { ProfilePage } from './pages/ProfilePage';
import { ResetPasswordPage } from './pages/ResetPasswordPage';
import { DashboardPage } from './pages/DashboardPage';
import { CreateCasePage } from './pages/CreateCasePage';
import { AlertsPage } from './pages/AlertsPage';
import { GeolocationPage } from './pages/GeolocationPage';
import { CollaborativeNetworkPage } from './pages/CollaborativeNetworkPage';
import { UserCasesPage } from './pages/UserCasesPage';
import { ManageUsersPage } from './pages/admin/ManageUsersPage';
import { PermissionsPage } from './pages/admin/PermissionsPage';
import { SettingsPage } from './pages/admin/SettingsPage';
import { ReportsPage } from './pages/admin/ReportsPage';
import { PatternAnalysisPage } from './pages/admin/PatternAnalysisPage';
import { ActivityLogsPage } from './pages/admin/ActivityLogsPage';
import { ManageBadgesPage } from './pages/admin/ManageBadgesPage';
import { DuplicatesPage } from './pages/admin/DuplicatesPage';
import { ReportsFlowPage } from './pages/admin/ReportsFlowPage';
import { PartnersPage } from './pages/admin/PartnersPage';
import { ImageAnalysisPage } from './pages/admin/ImageAnalysisPage';
import { InstitutionalContentPage } from './pages/admin/InstitutionalContentPage';
import { SystemConfigPage } from './pages/admin/SystemConfigPage';
import { DeletedCasesPage } from './pages/admin/DeletedCasesPage';
import { BackupsPage } from './pages/admin/BackupsPage';
import { AnnouncementsPage } from './pages/admin/AnnouncementsPage';
import { NotificationConfigPage } from './pages/admin/NotificationConfigPage';
import { InfoPage } from './pages/InfoPage';
import { ProtectedRoute } from './components/ProtectedRoute';
function App() {
    return (_jsxs("div", { className: "min-h-screen bg-slate-50", children: [_jsx(Header, {}), _jsx("main", { className: "mx-auto max-w-6xl px-4 py-10", children: _jsxs(Routes, { children: [_jsx(Route, { path: "/", element: _jsx(HomePage, {}) }), _jsx(Route, { path: "/informacoes", element: _jsx(InfoPage, {}) }), _jsx(Route, { path: "/entrar", element: _jsx(LoginPage, {}) }), _jsx(Route, { path: "/registar", element: _jsx(RegisterPage, {}) }), _jsx(Route, { path: "/recuperar-senha", element: _jsx(ResetPasswordPage, {}) }), _jsx(Route, { path: "/dashboard", element: _jsx(DashboardPage, {}) }), _jsx(Route, { path: "/casos/novo", element: _jsx(CreateCasePage, {}) }), _jsx(Route, { path: "/casos", element: _jsx(CasesPage, {}) }), _jsx(Route, { path: "/casos/:id", element: _jsx(CaseDetailsPage, {}) }), _jsx(Route, { path: "/analise", element: _jsx(AnalyticsPage, {}) }), _jsx(Route, { path: "/voluntariado", element: _jsx(VolunteerPage, {}) }), _jsx(Route, { path: "/perfil", element: _jsx(ProfilePage, {}) }), _jsx(Route, { path: "/alertas", element: _jsx(AlertsPage, {}) }), _jsx(Route, { path: "/geolocalizacao", element: _jsx(GeolocationPage, {}) }), _jsx(Route, { path: "/rede-colaborativa", element: _jsx(CollaborativeNetworkPage, {}) }), _jsx(Route, { path: "/usuarios/:userId/casos", element: _jsx(UserCasesPage, {}) }), _jsx(Route, { path: "/admin/usuarios", element: _jsx(ProtectedRoute, { allowedRoles: ['ADMIN'], children: _jsx(ManageUsersPage, {}) }) }), _jsx(Route, { path: "/admin/permissoes", element: _jsx(ProtectedRoute, { allowedRoles: ['ADMIN'], children: _jsx(PermissionsPage, {}) }) }), _jsx(Route, { path: "/admin/configuracoes", element: _jsx(ProtectedRoute, { allowedRoles: ['ADMIN'], children: _jsx(SettingsPage, {}) }) }), _jsx(Route, { path: "/admin/relatorios", element: _jsx(ProtectedRoute, { allowedRoles: ['ADMIN'], children: _jsx(ReportsPage, {}) }) }), _jsx(Route, { path: "/admin/analise-padroes", element: _jsx(ProtectedRoute, { allowedRoles: ['ADMIN'], children: _jsx(PatternAnalysisPage, {}) }) }), _jsx(Route, { path: "/admin/logs", element: _jsx(ProtectedRoute, { allowedRoles: ['ADMIN'], children: _jsx(ActivityLogsPage, {}) }) }), _jsx(Route, { path: "/admin/badges", element: _jsx(ProtectedRoute, { allowedRoles: ['ADMIN'], children: _jsx(ManageBadgesPage, {}) }) }), _jsx(Route, { path: "/admin/duplicados", element: _jsx(ProtectedRoute, { allowedRoles: ['ADMIN', 'MODERADOR'], children: _jsx(DuplicatesPage, {}) }) }), _jsx(Route, { path: "/admin/denuncias-fluxo", element: _jsx(ProtectedRoute, { allowedRoles: ['ADMIN', 'MODERADOR'], children: _jsx(ReportsFlowPage, {}) }) }), _jsx(Route, { path: "/admin/parceiros", element: _jsx(ProtectedRoute, { allowedRoles: ['ADMIN', 'MODERADOR'], children: _jsx(PartnersPage, {}) }) }), _jsx(Route, { path: "/admin/analise-imagens", element: _jsx(ProtectedRoute, { allowedRoles: ['ADMIN', 'MODERADOR'], children: _jsx(ImageAnalysisPage, {}) }) }), _jsx(Route, { path: "/admin/conteudo-institucional", element: _jsx(ProtectedRoute, { allowedRoles: ['ADMIN'], children: _jsx(InstitutionalContentPage, {}) }) }), _jsx(Route, { path: "/admin/configuracoes-sistema", element: _jsx(ProtectedRoute, { allowedRoles: ['ADMIN'], children: _jsx(SystemConfigPage, {}) }) }), _jsx(Route, { path: "/admin/casos-deletados", element: _jsx(ProtectedRoute, { allowedRoles: ['ADMIN'], children: _jsx(DeletedCasesPage, {}) }) }), _jsx(Route, { path: "/admin/backups", element: _jsx(ProtectedRoute, { allowedRoles: ['ADMIN'], children: _jsx(BackupsPage, {}) }) }), _jsx(Route, { path: "/admin/comunicados", element: _jsx(ProtectedRoute, { allowedRoles: ['ADMIN'], children: _jsx(AnnouncementsPage, {}) }) }), _jsx(Route, { path: "/admin/notificacoes", element: _jsx(ProtectedRoute, { allowedRoles: ['ADMIN'], children: _jsx(NotificationConfigPage, {}) }) })] }) })] }));
}
export default App;
